import { generateText } from 'ai';
import { openai } from '@ai-sdk/openai';
import { createCodeExecutionTool } from '../src/code-execution-tool';

(async () => {
  // Create tool with default settings (per_execution strategy)  - we set it to per_session to reuse the same container for multiple executions and to have access to the generated files
  const { codeExecutionTool, cleanup, executionEngine } = createCodeExecutionTool({ defaultStrategy: 'per_session' });
  executionEngine.setVerbosity('info');
  try {
    console.log('Generating python script...');
    const res = await generateText({
      model: openai('gpt-4o'),
      maxSteps: 1,
      messages: [
        {
          role: 'user',
          content:
            'Write a Python script that generates random nice looking chart and saves a PNG or SVG chart of temperature change to /workspace/weather.png. Run this code only once with the codeExecutionTool. Pass all required libraries (eg. matplotlib) as dependencies to the tool to be installed by "pip install".' // instruction for AI
        }
      ],
      tools: { codeExecutionTool },
      toolChoice: 'required'
    });

    console.log('AI response:', res.text);
    console.log('Execution results:', res.toolResults);

    const toolRes = (res.toolResults?.[0] as any)?.result;
    if (toolRes) {
      console.log('Generated files:', toolRes.generatedFiles);
    }
  } finally {
    await cleanup(true); // -- after using the files generated by the tool, we can cleanup the container - it will delete the container and the workspace - true means we're keeping the generated files
  }
})(); 